version: '3.5'

networks:
  basic:
    driver: bridge
    name: t3-api

services:
  t3-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: t3-api
    container_name: t3-api    
    ports:
      - "${API_PORT}:7000"
    volumes:
      - .:/app
    networks:
      - basic   